Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    main()
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    rv = self.invoke(ctx)
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    mkdir(name, mode)
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    mkdir(name, mode)
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return __callback(*args, **kwargs)
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 281, in main
    os.makedirs(path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/AuMieSphere/AuMie/15)TUPAC/1NodeTest/1NodeRes2'
srun: error: cnode42: tasks 0-3,5-24,26-38,40-41,43-63: Exited with exit code 1
Traceback (most recent call last):
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 985, in <module>
    main()
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/home/vpais/ThesisPython/./AuMieSphere/u_au_mie_scattering.py", line 461, in main
    flux_path =  vm.save_midflux(sim, box_x1, box_x2, box_y1, 
  File "/nfs/home/vpais/ThesisPython/v_meep.py", line 244, in save_midflux
    os.makedirs(new_flux_path)
  File "/nfs/home/vpais/miniconda/envs/pmp/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/nfs/home/vpais/ThesisResults/FluxData/MidFlux20210724113050'
srun: error: cnode42: task 42: Exited with exit code 1
srun: got SIGCONT
slurmstepd: error: *** STEP 380744.0 ON cnode42 CANCELLED AT 2021-07-24T11:49:51 ***
slurmstepd: error: *** JOB 380744 ON cnode42 CANCELLED AT 2021-07-24T11:49:51 ***
srun: forcing job termination
